version: '2.0'

services:

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8181:8080"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin"
      DB_VENDOR: h2

#    volumes:
#      - ./src/test/resources/docker-compose/keycloak-import.json:/opt/keycloak/data/import
