version: '2.0'

services:

  postgresql:
    image: quay.io/coreos/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled"
      DB_VENDOR: h2

    volumes:
      - ./src/test/resources/docker-compose/keycloak-import.json:/tmp/realm.json
